### ISSUE TITLE
信息盒子还没上线吗

### ISSUE THREAD

**Issue by ethanchengyu** [lcomplete/coderinfo#1]
http://rssletter.xyz
发现怎么都是无法访问🤣

**Comment by lcomplete** [comment]
> http://rssletter.xyz
> 
> 发现怎么都是无法访问🤣

服务器退了，🤣

**Comment by ethanchengyu** [comment]
懂了，
从过去到现在还是缺公众号到rss渠道呢
有点可惜

**Comment by lcomplete** [comment]
> 懂了，
> 从过去到现在还是缺公众号到rss渠道呢
> 有点可惜
> 

这个老代码也用不了了，现在这类渠道应该非常多，你看看 rsshub 支持不。
